# Generated by Django 2.1.4 on 2018-12-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20181220_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_sys',
            name='cpu_status',
            field=models.FloatField(default=0, max_length=8, verbose_name='cpu状态'),
        ),
        migrations.AlterField(
            model_name='tbl_sys',
            name='currCpu',
            field=models.FloatField(default=0, max_length=8, verbose_name='当前cpu使用率'),
        ),
        migrations.AlterField(
            model_name='tbl_sys',
            name='currDisk',
            field=models.FloatField(default=0, max_length=8, verbose_name='当前disk使用率'),
        ),
        migrations.AlterField(
            model_name='tbl_sys',
            name='currMem',
            field=models.FloatField(default=0, max_length=8, verbose_name='当前Mem使用率'),
        ),
        migrations.AlterField(
            model_name='tbl_sys',
            name='curr_rx',
            field=models.FloatField(default=0, max_length=8, verbose_name='当前接收流量'),
        ),
        migrations.AlterField(
            model_name='tbl_sys',
            name='curr_tx',
            field=models.FloatField(default=0, max_length=8, verbose_name='当前下行流量'),
        ),
        migrations.AlterField(
            model_name='tbl_sys',
            name='disk_status',
            field=models.FloatField(default=0, max_length=8, verbose_name='cpu状态'),
        ),
        migrations.AlterField(
            model_name='tbl_sys',
            name='mem_status',
            field=models.FloatField(default=0, max_length=8, verbose_name='cpu状态'),
        ),
        migrations.AlterField(
            model_name='tbl_sys',
            name='rx_status',
            field=models.FloatField(default=0, max_length=8, verbose_name='上行流量趋势率'),
        ),
        migrations.AlterField(
            model_name='tbl_sys',
            name='tx_status',
            field=models.FloatField(default=0, max_length=8, verbose_name='下行流量趋势率'),
        ),
    ]
