# Generated by Django 2.1.4 on 2018-12-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20181220_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_sys',
            name='cpu_status',
            field=models.IntegerField(choices=[(0, '-'), (1, 'up'), (2, 'down')], default=0, verbose_name='cpu状态'),
        ),
        migrations.AlterField(
            model_name='tbl_sys',
            name='disk_status',
            field=models.IntegerField(choices=[(0, '-'), (1, 'up'), (2, 'down')], default=0, verbose_name='cpu状态'),
        ),
        migrations.AlterField(
            model_name='tbl_sys',
            name='mem_status',
            field=models.IntegerField(choices=[(0, '-'), (1, 'up'), (2, 'down')], default=0, verbose_name='cpu状态'),
        ),
        migrations.AlterField(
            model_name='tbl_sys',
            name='rx_status',
            field=models.IntegerField(choices=[(0, '-'), (1, 'up'), (2, 'down')], default=0, verbose_name='上行流量趋势率'),
        ),
        migrations.AlterField(
            model_name='tbl_sys',
            name='tx_status',
            field=models.IntegerField(choices=[(0, '-'), (1, 'up'), (2, 'down')], default=0, verbose_name='趋势状态'),
        ),
    ]
