# Generated by Django 2.1.4 on 2018-12-21 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20181220_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_sys',
            name='cpu_status',
        ),
        migrations.RemoveField(
            model_name='tbl_sys',
            name='disk_status',
        ),
        migrations.RemoveField(
            model_name='tbl_sys',
            name='mem_status',
        ),
        migrations.RemoveField(
            model_name='tbl_sys',
            name='rx_status',
        ),
        migrations.RemoveField(
            model_name='tbl_sys',
            name='tx_status',
        ),
    ]
