# Generated by Django 2.1.4 on 2018-12-22 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20181221_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=32, verbose_name='文件名')),
                ('filesize', models.CharField(max_length=8, verbose_name='文件大小')),
                ('filetype', models.IntegerField(choices=[(0, 'xml'), (1, 'csv'), (2, 'pcap')], verbose_name='文件类型')),
            ],
        ),
        migrations.CreateModel(
            name='resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathname', models.CharField(max_length=32, null=True, verbose_name='路径名')),
                ('filename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.files', verbose_name='文件名id')),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.resource', verbose_name='父级id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User', verbose_name='关联用户id')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('user', 'pathname', 'pid')},
        ),
    ]
