# Generated by Django 2.1.4 on 2018-12-22 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20181222_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='filename',
        ),
    ]
