# Generated by Django 2.1.4 on 2019-01-02 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_remove_resource_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_sipCfg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localPort', models.CharField(max_length=8, verbose_name='本端sipp端口')),
                ('remoteAddr', models.GenericIPAddressField(verbose_name='对端sip地址')),
                ('remotePort', models.CharField(max_length=8, verbose_name='对端sip端口')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User', verbose_name='关联用户')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_sys',
            name='port_list',
            field=models.CharField(max_length=1024, null=True, verbose_name='sip端口可用列表'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='app01.resource', verbose_name='父级id'),
        ),
    ]
