# Generated by Django 2.1.4 on 2019-01-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20190102_0349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_task',
            old_name='task_name',
            new_name='taskName',
        ),
        migrations.AddField(
            model_name='tbl_task',
            name='callRoute',
            field=models.CharField(max_length=32, null=True, verbose_name='呼叫路由'),
        ),
        migrations.AddField(
            model_name='tbl_task',
            name='callType',
            field=models.IntegerField(null=True, verbose_name='呼叫类型'),
        ),
        migrations.AddField(
            model_name='tbl_task',
            name='concurrentNum',
            field=models.IntegerField(null=True, verbose_name='初始呼叫并发数'),
        ),
        migrations.AddField(
            model_name='tbl_task',
            name='csvScript',
            field=models.CharField(max_length=32, null=True, verbose_name='csv脚本名称'),
        ),
        migrations.AddField(
            model_name='tbl_task',
            name='decreaseConNum',
            field=models.CharField(max_length=32, null=True, verbose_name='递减并发数'),
        ),
        migrations.AddField(
            model_name='tbl_task',
            name='decreaseTime',
            field=models.CharField(max_length=32, null=True, verbose_name='开始递减时间'),
        ),
        migrations.AddField(
            model_name='tbl_task',
            name='dirPath',
            field=models.CharField(max_length=128, null=True, verbose_name='脚本所在目录'),
        ),
        migrations.AddField(
            model_name='tbl_task',
            name='increaseConNum',
            field=models.CharField(max_length=32, null=True, verbose_name='递增并发数'),
        ),
        migrations.AddField(
            model_name='tbl_task',
            name='increaseTime',
            field=models.CharField(max_length=32, null=True, verbose_name='开始递增时间'),
        ),
        migrations.AddField(
            model_name='tbl_task',
            name='lastForCallTime',
            field=models.CharField(max_length=32, null=True, verbose_name='呼叫时长'),
        ),
        migrations.AddField(
            model_name='tbl_task',
            name='localControlPort',
            field=models.CharField(max_length=5, null=True, verbose_name='本地远程控制端口'),
        ),
        migrations.AddField(
            model_name='tbl_task',
            name='lostRate',
            field=models.FloatField(max_length=3, null=True, verbose_name='丢包率'),
        ),
        migrations.AddField(
            model_name='tbl_task',
            name='startTime',
            field=models.CharField(max_length=32, null=True, verbose_name='任务创建时间'),
        ),
        migrations.AddField(
            model_name='tbl_task',
            name='xmlScript',
            field=models.CharField(max_length=32, null=True, verbose_name='xml脚本名称'),
        ),
    ]
