# Generated by Django 2.1.4 on 2019-01-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20190108_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_sys',
            name='currentConNum',
            field=models.IntegerField(null=True, verbose_name='系统当前总呼叫并发数'),
        ),
    ]
