# Generated by Django 2.1.4 on 2019-01-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_tbl_sys_currentconnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_sys',
            name='currentConNum',
            field=models.IntegerField(default=0, verbose_name='系统当前总呼叫并发数'),
        ),
    ]
