# Generated by Django 2.1.4 on 2019-01-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_auto_20190108_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_sipcfg',
            name='isRunning',
            field=models.BooleanField(default=False, verbose_name='正在使用标志位'),
        ),
    ]
