# Generated by Django 2.1.4 on 2019-01-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_tbl_sipcfg_isrunning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_task',
            name='lostRate',
            field=models.IntegerField(null=True, verbose_name='丢包率'),
        ),
    ]
