# Generated by Django 2.1.4 on 2019-01-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_auto_20190108_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_task',
            name='decreaseConNum',
            field=models.IntegerField(null=True, verbose_name='递减并发数'),
        ),
        migrations.AlterField(
            model_name='tbl_task',
            name='increaseConNum',
            field=models.IntegerField(null=True, verbose_name='递增并发数'),
        ),
    ]
