# Generated by Django 2.1.4 on 2019-01-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_auto_20190108_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_task',
            name='endTime',
            field=models.CharField(max_length=32, null=True, verbose_name='任务结束时间'),
        ),
    ]
