# Generated by Django 2.1.4 on 2019-01-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_tbl_task_endtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_task',
            name='taskStatus',
            field=models.IntegerField(default=0, verbose_name='任务状态'),
        ),
    ]
