# Generated by Django 2.1.4 on 2019-01-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_tbl_task_taskstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_task',
            name='timeOptions',
            field=models.IntegerField(default=0, verbose_name='呼叫执行阶段，恒并对，递增，递减'),
        ),
    ]
