# Generated by Django 2.1.4 on 2019-01-11 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_tbl_task_timeoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentCallNum', models.IntegerField(default=0, verbose_name='当前呼叫数')),
                ('avgCallLength', models.CharField(max_length=8, null=True, verbose_name='平均通话时长')),
                ('asr', models.FloatField(null=True, verbose_name='接通率，access success ratio')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_task',
            name='callLength',
            field=models.CharField(max_length=8, null=True, verbose_name='总通话时长'),
        ),
        migrations.AddField(
            model_name='tbl_task',
            name='callRate',
            field=models.CharField(max_length=12, null=True, verbose_name='当前任务cps'),
        ),
        migrations.AddField(
            model_name='tbl_task',
            name='elapsedTime',
            field=models.CharField(max_length=8, null=True, verbose_name='当前任务已呼叫时长'),
        ),
        migrations.AddField(
            model_name='tbl_task',
            name='errorReason',
            field=models.TextField(null=True, verbose_name='失败原因字符串'),
        ),
        migrations.AddField(
            model_name='tbl_task',
            name='failedCallNum',
            field=models.IntegerField(null=True, verbose_name='当前任务呼叫失败数'),
        ),
        migrations.AddField(
            model_name='tbl_task',
            name='msgLog',
            field=models.TextField(null=True, verbose_name='消息日志字符串'),
        ),
        migrations.AddField(
            model_name='tbl_task',
            name='successfulCallNum',
            field=models.IntegerField(null=True, verbose_name='当前任务呼叫成功数'),
        ),
        migrations.AddField(
            model_name='tbl_task',
            name='totalCallCreatedNum',
            field=models.IntegerField(null=True, verbose_name='当前任务已呼叫总数'),
        ),
        migrations.AddField(
            model_name='tbl_stat',
            name='taskId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.tbl_task', verbose_name='task标识'),
        ),
    ]
