# Generated by Django 2.1.4 on 2019-01-12 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_auto_20190111_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_stat',
            old_name='taskId',
            new_name='taskPk',
        ),
    ]
