# Generated by Django 2.1.4 on 2019-01-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0026_auto_20190113_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_stat',
            name='cpuRate',
            field=models.FloatField(default=0, max_length=8, null=True, verbose_name='cpu利用率'),
        ),
    ]
