# Generated by Django 2.1.4 on 2019-01-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0027_tbl_stat_cpurate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_sys',
            name='currentCps',
            field=models.IntegerField(default=0, verbose_name='当前系统总的cps'),
        ),
    ]
