# Generated by Django 2.1.4 on 2019-01-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0028_tbl_sys_currentcps'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_task',
            name='qFlag',
            field=models.BooleanField(default=False, verbose_name='是否发送过q的标志位'),
        ),
    ]
