# Generated by Django 2.1.4 on 2019-01-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0029_tbl_task_qflag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_stat',
            name='cpuRate',
        ),
        migrations.AddField(
            model_name='tbl_stat',
            name='callRate',
            field=models.IntegerField(default=0, verbose_name='当前任务cps'),
        ),
        migrations.AddField(
            model_name='tbl_sys',
            name='countTime',
            field=models.CharField(max_length=19, null=True, verbose_name='数据生成时间'),
        ),
    ]
