# Generated by Django 2.1.4 on 2019-01-15 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0030_auto_20190115_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_sys',
            name='cpu_rate',
        ),
        migrations.RemoveField(
            model_name='tbl_sys',
            name='disk_rate',
        ),
        migrations.RemoveField(
            model_name='tbl_sys',
            name='mem_rate',
        ),
        migrations.RemoveField(
            model_name='tbl_sys',
            name='rx_rate',
        ),
        migrations.RemoveField(
            model_name='tbl_sys',
            name='tx_rate',
        ),
    ]
