# Generated by Django 2.1.4 on 2019-02-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0034_auto_20190115_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
    ]
